version : "3.8"
services:
  mydb:
    platform: linux/x86_64
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=database
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    ports:
      - 3306:3306
  app:
    depends_on:
      - mydb
    build: ./java
    ports:
      - 8080:8080
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  :"jdbc:mysql://docker-mysql:3306/database?autoReconnect=true&useSSL=false",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "suraj",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "update"
      }'
    stdin_open: true
    tty: true
    
